stackName: quicksight-migrations-infra-dev
# Account numbers loaded from environment variables for security
awsAccount: "${AWS_SOURCE_ACCOUNT}"    
awsRegion: "us-east-1"        

bucket:
  name: "quicksight-source-s3-bc-cfn"   
  versioned: true

lambda:
  functionName: "quicksight-export-assets-lambda-cfn"
  runtime: "python3.10"
  timeout: 180

# NEW: target account/bucket (where you want the files written)
target:
  awsAccount: "${AWS_TARGET_ACCOUNT}"           
  awsRegion:  "us-east-1"
  bucket:
    name: "quicksight-asset-bundles-target-cfn"
    versioned: true
  allowPutObjectAcl: false  
